[general]
name = "fused-rms-norm"
backends = ["metal"]

[torch]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.fused_rms_norm_metal]
backend = "metal"
metal-std-version = "metal3.1"
src = [
  "fused-rms-norm-metal/rms_norm.metal",
  "fused-rms-norm-metal/rms_norm.mm",
  "fused-rms-norm-metal/utils.metal",
]
depends = ["torch"]
